name: Push Mirror to GitLab

on:
  push:
    branches:
      - main  # Change this to master if that is your primary branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          # Notice we are using ssh:// format now
          target_repo_url: "ssh://git@://gitlab.com"
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
