name: Push Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: "https://gitlab.com"
          auth_username: "oauth2"  # Change this to oauth2
          auth_password: ${{ secrets.GITLAB}}
